apps/balance/urls.py
from django.conf.urls import url

from . import views

#/balance/
urlpatterns = [   
    url(r'^$',views.MainBalanceRedirectView.as_view(),name="main_redirect"),
    url(r'^(?P<year>[0-9]{4})/$',views.YearlyMonthBalanceView.as_view(),name="year"),    
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.MonthBalanceView.as_view(),name="details"),
     url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/clear/$',views.ClearMonthBalanceView.as_view(),name="clear"),
     url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/clear/changed/$',views.ClearMonthBalanceChangedView.as_view(),name="clear_changed"),
    
    ]

apps/expenses/urls.py
from django.conf.urls import include, url

from . import views

#/expenses/
urlpatterns = [
    
    url(r'^$', views.MainExpensesRedirectView.as_view(),name='main_redirect'),
    
    # expense
    url(r'^(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', views.ExpenseView.as_view(),name='details'),
    url(r'^add/$', views.AddExpenseView.as_view(),name='add'),
    url(r'^edit/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', views.EditExpenseView.as_view(),name='edit'),
    url(r'^delete/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', views.DeleteExpenseView.as_view(),name='delete'),
    url(r'^approve/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', views.ApproveExpenseView.as_view(),name='approve'),
    url(r'^change-balanced-month/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$',views.ChangeExpenceBalanceMonthView.as_view(),name='change_month_balance'),
    
    # ajax
    url(r'^ajax/multi-approve/$', views.expenses_multiple_approve,name='expenses_multi_approve'),
    
    # list views
    # GET arg ?approve=yes/no/all by=all/my/divorcee
    url(r'^monthly/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.MonthlyExpensesAllView.as_view(),name='monthly_all'),
    url(r'^monthly/my/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.MonthlyExpensesMyView.as_view(),name='monthly_my'),
    url(r'^monthly/divorcee/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.MonthlyExpensesDivorceeView.as_view(),name='monthly_divorcee'),
    
    
]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles import views
from django.conf.urls.static import static

from django.contrib.auth import views as django_auth_views

from home.views import HomePageView
from apps.help import views as help_views
from apps.public.auth import views as auth_views
from apps.public.info import views as public_info_views
from apps.search.views import SearchView

urlpatterns = [
    # admin
    url(r'^%s/'%settings.ADMIN_URL, include(admin.site.urls)),
    
    # home
    url(r'^$', HomePageView.as_view(), name='home_page'),
    
    # auth
    url(r'^demo/$', auth_views.demo_account, name='demo_account'),
    url(r'^sign-up/$', auth_views.SignUpView.as_view(), name='sign_up_simple'),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login_simple'),
    url(r'^logout/$', auth_views.logout_user, name='logout_simple'),
    url(r'^reset-password/$',auth_views.password_reset_view,name="reset_password"),    
    
    # django auth
    url(r'^reset-password/done/$', django_auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        django_auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', django_auth_views.password_reset_complete, name='password_reset_complete'),
    
    # app modules
    url(r'^settings/', include('site_repo.apps.users.urls',namespace='users')),
    url(r'^expenses/', include('site_repo.apps.expenses.urls',namespace='expenses')),
    url(r'^balance/', include('site_repo.apps.balance.urls',namespace='balance')),   
    url(r'^search/$',SearchView.as_view(),name='search_view'),
    
    url(r'^how-to/$',help_views.IntroView.as_view(),name='intro'),
    
    # public info
    url(r'^about/$',public_info_views.AboutPublicView.as_view(),name="about_public"),
    url(r'^terms-of-service/$',public_info_views.TOSPublicView.as_view(),name="tos_public"),
    url(r'^privacy/$',public_info_views.PrivacyPolicyView.as_view(),name="privacy_policy_public")
]

if settings.DEBUG:
    urlpatterns += [url(r'^static/(?P<path>.*)$', views.serve),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
    
    

apps/balance/models.py
from collections import namedtuple
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from ..accounts.models import Account
from ..expenses.models import Expense

from site_repo.django_add.validators import verify_month_int,verify_month_is_before_this_month
from ...utils.db import run_sql
from .sql import of_year,of_month, sort_clause


class BalanceAggregateManager(models.Manager):
    
    def _get_recs(self,user,year,approved,month=None):
        
        divorcee_id = 0 if user.divorcee == None else user.divorcee.id
        args = [user.account.id,year,year,
                user.id,year,divorcee_id]
        approved_clause={'all':"",'yes':" AND is_approved=1 ",'no': " AND is_approved=0 "}[approved]
       
        if month != None:
            sql = of_month
            args.append(month)
        else:
            sql = of_year + sort_clause
        recs = run_sql(sql.format(approved_clause=approved_clause),*args)
        Lresults = []
        for rec in recs:
            D = {'month_of_balance':rec[0],
                 'year_of_balance':year,
                 'user':user,
                 'user_sum':rec[3],
                 'divorcee_participate':rec[4],
                 'divorcee':user.divorcee,
                 'divorcee_sum':rec[7],
                 'user_participate':rec[8]
                 }
            D['user_sum'] = 0 if D['user_sum'] == None else D['user_sum']
            D['divorcee_participate'] = 0 if D['divorcee_participate'] == None else D['divorcee_participate']
            D['divorcee_sum'] = 0 if D['divorcee_sum'] == None else D['divorcee_sum']
            D['user_participate'] = 0 if D['user_participate'] == None else D['user_participate']
            D['user_net'] = D['user_sum'] + D['user_participate'] - D['divorcee_participate']
            D['divorcee_net'] = D['divorcee_sum'] + D['divorcee_participate'] - D['user_participate']
            D['total'] = D['user_sum'] + D['divorcee_sum']
            Lresults.append(D)
           
 
        q = self.model.objects.filter(year_of_balance=year,account=user.account,
                                     month_of_balance__in=[m['month_of_balance'] for m in Lresults])
        Dq = {balance_obj.month_of_balance:balance_obj for balance_obj in q}
        for Dbalance in Lresults:
            obj = Dq[Dbalance['month_of_balance']]
            Dbalance['balance_object']  = obj
            Dbalance['cleared'] = obj.divorcee1 != None and obj.divorcee2 != None
            
        return Lresults
    
    def by_month(self,user,year,month,approved="all"):
        
        return self._get_recs(user, int(year),approved, int(month))[0]
    
    def by_year(self,user,year,approved="all"):
        
        return self._get_recs(user, int(year),approved)
    
class Objects(models.Manager):
    pass
                        

class MonthlyBalance(models.Model):
    
    class Meta:
            unique_together =('month_of_balance','year_of_balance','account')  
    
    month_of_balance = models.IntegerField(validators=[verify_month_int])
    year_of_balance = models.IntegerField()
    
    account = models.ForeignKey(Account,related_name="months_balanced")
    
    divorcee1 = models.ForeignKey(User,blank=True,null=True,related_name="divorcee1_balance")
    divorcee2 = models.ForeignKey(User,blank=True,null=True,related_name="divorcee2_balance")
    
    is_balanced = models.BooleanField(default=False)
    
    balance_aggregate = BalanceAggregateManager()
    objects = Objects() # not avialable w/o explicit assignment when other manager assigned
    
    def save(self,*args,**kwargs):
        
        if not kwargs.get('force_insert',False):
            # can not balance an account for a month before the month finishes
            verify_month_is_before_this_month(self.year_of_balance,self.month_of_balance)
        
        return super(MonthlyBalance,self).save(*args,**kwargs)
        
        
    
    
    def get_absolute_url(self):
        
        return reverse("balance:details",kwargs={'year':self.year_of_balance,
                                                 'month':self.month_of_balance})
    
    def divorcee_cleared_month(self,user):
        
        if user != None:
            return self.divorcee1 == user or self.divorcee2 == user
        else:
            return False
        
    def calcs(self,user):
        a = self.account
        divorcee1_sum = expenses.filter(month_balanced=self.month_of_balance,
                                   year_balanced=self.year_of_balance,
                                   owner=a.divorcee1).aggregate(Sum('expense_sum'),)
    
    
@receiver(post_save,sender=Expense)
def first_expense_for_month(*args,**kwargs):
    
    if not kwargs['created']:
        return
    
    expense = kwargs['instance']
    Dcriteria = {'month_of_balance':expense.month_balanced,
                 'year_of_balance':expense.year_balanced,
                 'account':expense.account}
    try:
        m = MonthlyBalance.objects.get(**Dcriteria)
    except ObjectDoesNotExist:        
        m = MonthlyBalance(**Dcriteria)
        m.save(force_insert=True)

apps/balance/views.py
import datetime
from django.conf import settings
from django.core.urlresolvers import reverse
from django.shortcuts import render,redirect
from django.views import generic


from ...lang import balance as lang_balance
from ...django_add.validators import verify_month_is_before_this_month

from .helpers import clear_month_balance
from .models import MonthlyBalance

class MainBalanceRedirectView(generic.RedirectView):
    
    def get_redirect_url(self):
        
        n = datetime.datetime.today()
        return reverse("balance:year",kwargs={'year':n.year})
        
class ClearMonthBalanceChangedView(generic.DetailView):     
    
    
    def get(self,request,*args,**kwargs):
        
        year = int(self.kwargs['year'])
        month = int(self.kwargs['month'])
        assert verify_month_is_before_this_month(year,month)
        cleared = {'cleared':True,'not-cleared':False}[request.GET['changed-to']]
        balance = clear_month_balance(user=request.user,
                                      month=month,
                                      year=year,
                                      cleared=cleared)
    
        return redirect(balance)  
        
            
        
        

class ClearMonthBalanceView(generic.DetailView):
    
    model = MonthlyBalance
    template_name = "balance/monthly_balance_clear.html"
    context_object_name = 'balance'
    
    def get_object(self):
        
        year = int(self.kwargs['year'])
        month = int(self.kwargs['month'])
        assert verify_month_is_before_this_month(year,month)        
            
        obj = MonthlyBalance.balance_aggregate.by_month(user=self.request.user,
                                                               year=self.kwargs['year'],
                                                               month=self.kwargs['month'],
                                                               approved="yes")
            
           
            
        return obj
        
    def get_context_data(self,*args,**kwargs):
        
        context = super(ClearMonthBalanceView,self).get_context_data(*args,**kwargs)
        
        L = [self.object['balance_object'].divorcee1,self.object['balance_object'].divorcee2]
        me_cleared = lang_balance.cleared if self.request.user in L else lang_balance.not_cleared
        divorcee_cleared = lang_balance.cleared if self.request.user.divorcee in L else lang_balance.not_cleared
        context['user_cleared'] = self.request.user in L
        context['me_cleared'] = me_cleared%self.request.user.username
        if self.request.user.divorcee:
            context['divorcee_cleared'] = divorcee_cleared%self.request.user.divorcee.username 
        else:
            context['divorcee_cleared'] = ""
            
        context["pay"] = self.object['user_participate'] - self.object['divorcee_participate']
        
        return dict(context,**self.kwargs)
        

class YearlyMonthBalanceView(generic.ListView):
    
    template_name = 'balance/monthly_balance_year.html'
    
    def get_queryset(self):
        
        self.approved = self.request.GET.get('approved','all')
        assert self.approved in ['all','yes','no']
        queryset = MonthlyBalance.balance_aggregate.by_year(self.request.user,self.kwargs['year'],self.approved)
        return queryset
    
    def get_context_data(self,*args,**kwargs):
        
        context = super(YearlyMonthBalanceView,self).get_context_data(*args,**kwargs)
        context['select_years'] = settings.YEARS_TO_FILTER_ON_GUI
        context['approved'] =  {'all':'All','yes': 'Approved','no':'Not Approved'}[self.approved]
        return dict(context,**self.kwargs)


class MonthBalanceView(generic.DetailView):
    
    model = MonthlyBalance
    template_name = 'balance/monthly_balance_details.html'
    context_object_name = 'balance'

    def get_object(self):
        
        self.approved = self.request.GET.get('approved','all')
        assert self.approved in ['all','yes','no']        
        object = MonthlyBalance.balance_aggregate.by_month(user=self.request.user,
                                                           year=self.kwargs['year'],
                                                           month=self.kwargs['month'],
                                                           approved=self.approved)
        
        return object
    
    def get_context_data(self,*args,**kwargs):
                    
        context = super(MonthBalanceView,self).get_context_data(*args,**kwargs)
        
        L = [self.object['balance_object'].divorcee1,self.object['balance_object'].divorcee2]
        me_cleared = lang_balance.cleared if self.request.user in L else lang_balance.not_cleared
        divorcee_cleared = lang_balance.cleared if self.request.user.divorcee in L else lang_balance.not_cleared
        context['me_cleared'] = me_cleared%self.request.user.username
        if self.request.user.divorcee:
            context['divorcee_cleared'] = divorcee_cleared%self.request.user.divorcee.username 
        else:
            context['divorcee_cleared'] = ""
       
        context['approved'] =  {'all':'All','yes': 'Approved','no':'Not Approved'}[self.approved]
        year = int(self.kwargs['year'])
        month = int(self.kwargs['month'])
        context['can_clear'] = verify_month_is_before_this_month(year,month,raise_exception=False) 
        
        context["pay"] = self.object['user_participate'] - self.object['divorcee_participate']
             
        return dict(context,**self.kwargs)    
                

templates/balance/monthly_balance_clear.html
{% extends "base_login.html" %}
{% load static from staticfiles %}
{% load global_tags %}

{% block sidebar_item %} "balance" {% endblock sidebar_item %}
{% block page_title %} Clear Monthly Balance  {% endblock page_title %}

{% block ready_script %} 
    {{ block.super }}
    redirect_url = "{% url 'balance:clear_changed' year month %}?changed-to=";
    
    {% if not DEMO %}
        $("#save_balance").on("click",function(){ 
            if ($("#change_to:checked").length>0)
                {window.location.replace(redirect_url+"cleared");}
            else
                {window.location.replace(redirect_url+"not-cleared");}
            });
    {% endif %}
{% endblock ready_script %}

{% block main_content %}

<div class="panel panel-primary">
  <div class="panel-body panel-heading">
    <h3 class="panel-title"> Balancing a Month: Agree to "close" a month, and pay each other the difference in costs. </h3>
  </div>
  <div class="panel-footer">
    Once you clear a month, there are no further changes to expenses in this month. The expenses status is "locked",
    assuming that you and your divorcee will clear the amount of the approved expenses.
  </div>
</div>

<div class="col-xs-6">
<h4> Approved Expenses for {{ balance.month_of_balance|intmonth }},{{ balance.year_of_balance }} </h4>

    <table class="table table-striped">
        <tbody>
        <tr>
            <td>My Expenses</td>
            <td>{{  balance.user_sum|currencyformat }} <td>
        </tr>
        
        </tr>
            <td>Divorcee Participate</td>
            <td>{{  balance.divorcee_participate|currencyformat }} <td>
        </tr>
        
        <tr> 
            <td>Divorcee Expenses</td>
            <td>{{  balance.divorcee_sum|currencyformat }} <td>
         </tr>
         
         <tr>
            <td>My Participate</td>
            <td>{{  balance.user_participate|currencyformat }} <td>
         </tr>
            
        <tr style="font-weight:bold;" class="info">
            <td>My Net Costs</td>
            <td>{{  balance.user_net|currencyformat }} <td>
        </tr>
           
          <tr>
                <td>Divorcee Net Costs</td> 
                 <td>{{  balance.divorcee_net|currencyformat }} <td>
          </tr>
          
          </tbody>
    
    </table>
    
          
      <div class="checkbox">
            
                    <label>
                        <input id="change_to" type="checkbox" class="checkbox" {% if user_cleared %} checked {% endif %}>  
                        <span style="font-size:large;"> I accept and clear this month </span>
                    </label>
            </div>    
       <a href="{{ balance.balance_object.get_absolute_url }}" class="btn btn-danger" role="button"> Cancel </a>
        <button id="save_balance" class="btn btn-success save"> Save </button>
            
            
            
            
 

    
</div>    
<div class="col-xs-1"></div>
<div class="col-xs-4">

{% include "elements/balance_pay.html" %}<br>
            <h4> <span class="label label-info p-r-10"> Balance Status </span></h4>                      
            <h4> {{ me_cleared }} </h4>
            <h4>  {{ divorcee_cleared}} </h4>
    
</div>



{% endblock main_content %}

templates/balance/monthly_balance_details.html
{% extends "base_login.html" %}
{% load static from staticfiles %}
{% load global_tags %}

{% block sidebar_item %} "balance" {% endblock sidebar_item %}
{% block page_title %} Monthly Balance  {% endblock page_title %}

{% block page_nav %}
    {% include "elements/dropdown_select_approved_balance.html" %}
{% endblock page_nav %}

{% block main_content %}
<div class="col-xs-6">
<h4> {{ balance.month_of_balance|intmonth }},{{ balance.year_of_balance }} </h4>

    <table class="table table-striped">
        <tbody>
        <tr>
            <td>My Expenses</td>
            <td>{{  balance.user_sum|currencyformat }} <td>
        </tr>
        
        </tr>
            <td>Divorcee Participate</td>
            <td>{{  balance.divorcee_participate|currencyformat }} <td>
        </tr>
        
        <tr> 
            <td>Divorcee Expenses</td>
            <td>{{  balance.divorcee_sum|currencyformat }} <td>
         </tr>
         
         <tr>
            <td>My Participate</td>
            <td>{{  balance.user_participate|currencyformat }} <td>
         </tr>
            
        <tr style="font-weight:bold;" class="info">
            <td>My Net Costs</td>
            <td>{{  balance.user_net|currencyformat }} <td>
        </tr>
           
          <tr>
                <td>Divorcee Net Costs</td> 
                 <td>{{  balance.divorcee_net|currencyformat }} <td>
          </tr>
          
          </tbody>
    
    </table>
    
          
          
            
            
            
            
 <h4> <span class="label label-info p-r-10"> Balance Status </span></h4>           
           
            <h4> {{ me_cleared }} </h4>
            <h4>  {{ divorcee_cleared}} </h4>
            
            {% if can_clear %}
                <a href="{% url "balance:clear" year month %}" class="btn btn-primary pull-right" role="button"> Change Balance Status</a>
            {% else %}
                 <h4> <span class="label label-info p-r-10"> You can clear a month after it finishes </span></h4>
            {% endif %}
</div>    

<div class="col-xs-1"></div>
<div class="col-xs-5">
    {% include "elements/balance_pay.html" %}
</div>
{% endblock main_content %}

templates/balance/monthly_balance_year.html
{% extends "base_login.html" %}
{% load static from staticfiles %}
{% load global_tags %}

{% block sidebar_item %} "balance" {% endblock sidebar_item %}
{% block page_title %} Months Balance  {% endblock page_title %}

{% block page_nav %} 
    
    
   {% include "elements/dropdown_select_year_balance.html" %} 
   {% include "elements/dropdown_select_approved_balance.html" %}

{% endblock page_nav %}

{% block main_content %}

    <table class="table table-hover">
        <tr>
        
            <th> Month </th>
             <th> My Expenses </th>
              <th> Divorcee Participate </th>
              <th> Divorcee Expenses </th>
              <th> My Participate </th>
              <th> My Net </th>
              <th> Divorcee Net </th>
               <th> Total Expenses </th>
               <th> Status </th>
              
        </tr>
        {% for balance in object_list %}
            <tr>
            
                <td>
                    <a href="{{ balance.balance_object.get_absolute_url }}?approved=yes"> {{  balance.month_of_balance|intmonth }} </a>
                </td>
                <td>
                {% if balance.user_sum > 0 %}
                    <a href="{% url "expenses:monthly_all"  year balance.month_of_balance  %}?by=my"> 
                        {{  balance.user_sum|currencyformat }} 
                    </a>
                {% else %} 0 {% endif %}
                    
                </td>
                <td>{{  balance.divorcee_participate|currencyformat }} </td>
                <td>
                    {% if balance.divorcee_sum > 0 %}
                    <a href="{% url "expenses:monthly_all"  year balance.month_of_balance  %}?by=divorcee">
                        {{  balance.divorcee_sum|currencyformat }} 
                    </a>
                    {% else %} 0 {% endif %}
                    </td>
                <td>{{  balance.user_participate|currencyformat }} </td>
                <td>{{  balance.user_net|currencyformat }} </td>
                <td>{{  balance.divorcee_net|currencyformat }} </td>
                <td>
                    {% if balance.total > 0 %}
                        <a href="{% url "expenses:monthly_all"  year balance.month_of_balance %}">
                            {{  balance.total|currencyformat }}
                        </a>
                     {% else %} 0 {% endif %}
                </td>
                <td>  {{  balance.cleared|striftrue:"Cleared" }}  </td>
                
            </tr>
        
        {% endfor %}
    </table>

{% endblock main_content %}