apps/balance/urls.py
from django.conf.urls import url

from . import views

#/balance/
urlpatterns = [   
    url(r'^$',views.MainBalanceRedirectView.as_view(),name="main_redirect"),
    url(r'^(?P<year>[0-9]{4})/$',views.YearlyMonthBalanceView.as_view(),name="year"),    
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.MonthBalanceView.as_view(),name="details"),
     url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/clear/$',views.ClearMonthBalanceView.as_view(),name="clear"),
     url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/clear/changed/$',views.ClearMonthBalanceChangedView.as_view(),name="clear_changed"),
    
    ]

apps/expenses/urls.py
from django.conf.urls import include, url

from . import views

#/expenses/
urlpatterns = [
    
    url(r'^$', views.MainExpensesRedirectView.as_view(),name='main_redirect'),
    
    # expense
    url(r'^(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', views.ExpenseView.as_view(),name='details'),
    url(r'^add/$', views.AddExpenseView.as_view(),name='add'),
    url(r'^edit/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', views.EditExpenseView.as_view(),name='edit'),
    url(r'^delete/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', views.DeleteExpenseView.as_view(),name='delete'),
    url(r'^approve/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', views.ApproveExpenseView.as_view(),name='approve'),
    url(r'^change-balanced-month/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$',views.ChangeExpenceBalanceMonthView.as_view(),name='change_month_balance'),
    
    # ajax
    url(r'^ajax/multi-approve/$', views.expenses_multiple_approve,name='expenses_multi_approve'),
    
    # list views
    # GET arg ?approve=yes/no/all by=all/my/divorcee
    url(r'^monthly/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.MonthlyExpensesAllView.as_view(),name='monthly_all'),
    url(r'^monthly/my/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.MonthlyExpensesMyView.as_view(),name='monthly_my'),
    url(r'^monthly/divorcee/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.MonthlyExpensesDivorceeView.as_view(),name='monthly_divorcee'),
    
    
]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles import views
from django.conf.urls.static import static

from django.contrib.auth import views as django_auth_views

from home.views import HomePageView
from apps.help import views as help_views
from apps.public.auth import views as auth_views
from apps.public.info import views as public_info_views
from apps.search.views import SearchView

urlpatterns = [
    # admin
    url(r'^%s/'%settings.ADMIN_URL, include(admin.site.urls)),
    
    # home
    url(r'^$', HomePageView.as_view(), name='home_page'),
    
    # auth
    url(r'^demo/$', auth_views.demo_account, name='demo_account'),
    url(r'^sign-up/$', auth_views.SignUpView.as_view(), name='sign_up_simple'),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login_simple'),
    url(r'^logout/$', auth_views.logout_user, name='logout_simple'),
    url(r'^reset-password/$',auth_views.password_reset_view,name="reset_password"),    
    
    # django auth
    url(r'^reset-password/done/$', django_auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        django_auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', django_auth_views.password_reset_complete, name='password_reset_complete'),
    
    # app modules
    url(r'^settings/', include('site_repo.apps.users.urls',namespace='users')),
    url(r'^expenses/', include('site_repo.apps.expenses.urls',namespace='expenses')),
    url(r'^balance/', include('site_repo.apps.balance.urls',namespace='balance')),   
    url(r'^search/$',SearchView.as_view(),name='search_view'),
    
    url(r'^how-to/$',help_views.IntroView.as_view(),name='intro'),
    
    # public info
    url(r'^about/$',public_info_views.AboutPublicView.as_view(),name="about_public"),
    url(r'^terms-of-service/$',public_info_views.TOSPublicView.as_view(),name="tos_public"),
    url(r'^privacy/$',public_info_views.PrivacyPolicyView.as_view(),name="privacy_policy_public")
]

if settings.DEBUG:
    urlpatterns += [url(r'^static/(?P<path>.*)$', views.serve),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
    
    

templates/elements/balance_pay.html
{% load global_tags %}
<h4> <span class="label label-info p-r-10"> Pay </span></h4>
<h4>
{% if request.user.divorcee %}
    {% if pay > 0 %}
        I have to pay {{ user.divorcee.username }} {{ pay|currencyformat }}
    {% else %}    
        {{ user.divorcee.username }}  has to pay me {{ pay|abs_value|currencyformat }}
    {% endif %}
{% else %}
    When two divorcees use DivorceCalcs.com, you can see how much to pay each other to balance a month.
    <br> <br> Invite a divorcee by mail, with your account code (visible at your settings page).
{% endif %}
</h4>

templates/elements/dropdown_select_approved_balance.html
<div class="btn-group">
       <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Expenses: {{ approved }}   <span class="caret"></span>
       </button>
       <ul class="dropdown-menu">
               <li><a href="{{ request.path }}?approved=all">Expenses: All </a></li>
               <li><a href="{{ request.path }}?approved=yes">Expenses: Approved </a></li>
               <li><a href="{{ request.path }}?approved=no">Expenses: Not Approved </a></li>
       </ul>
</div>

templates/elements/dropdown_select_approved_expenses.html
<div class="btn-group">
       <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ approved }}   <span class="caret"></span>
       </button>
       <ul class="dropdown-menu">
               <li><a href="{{ request.path }}?approved=all&&{{ by_url_args }}">All </a></li>
               <li><a href="{{ request.path }}?approved=yes&&{{ by_url_args }}">Approved </a></li>
               <li><a href="{{ request.path }}?approved=no&&{{ by_url_args }}">Not Approved </a></li>
       </ul>
</div>

templates/elements/dropdown_select_month_expenses.html
{% load global_tags %}
<div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ month|intmonth }}  <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            {% for m in select_months %}
                <li>
                       <a href="{% url "expenses:monthly_all" year m%}?{{ approved_url_args }}&&{{ by_url_args }}">
                    {{ m|intmonth }} </a>                    
                </li>
            {% endfor %}
        </ul>
</div>

templates/elements/dropdown_select_owner_expenses.html
<div class="btn-group">
       <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ by }}   <span class="caret"></span>
       </button>
       <ul class="dropdown-menu">
               <li><a href="{{ request.path }}?by=all&&{{ approved_url_args }}">By All</a></li>
               <li><a href="{{ request.path }}?by=my&&{{ approved_url_args }}"> My </a></li>
               <li><a href="{{ request.path }}?by=divorcee&&{{ approved_url_args }}"> Divorcee </a></li>
       </ul>
</div>

templates/elements/dropdown_select_year_balance.html
<div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ year }}  <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            {% for y in select_years %}
                <li>
                    {% if request.GET.approved %}
                        <a href="{% url "balance:year" y %}?approved={{ request.GET.approved }}">
                    {% else %}
                        <a href="{% url "balance:year" y %}">
                    {% endif %}
                    {{ y }} </a>                    
                </li>
            {% endfor %}
        </ul>
</div>

templates/elements/dropdown_select_year_expenses.html
<div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ year }}  <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            {% for y in select_years %}
                <li>
                        <a href="{% url "expenses:monthly_all" y month %}?{{ approved_url_args }}&&{{ by_url_args }}">
                    {{ y }} </a>                    
                </li>
            {% endfor %}
        </ul>
</div>

templates/elements/login_modal.html
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="pull-right" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign-In</h4>
      </div>
      <form action='' method="POST" id="home_page_sign_in_form">
                        <div class="modal-body">
                    
                            {% csrf_token %}
                            <p>
                              <label for="id_username">Username:</label> 
                              <input id="id_username" maxlength="254" name="username" type="text" />
                            </p>
                            <p>
                              <label for="id_password">Password:</label> 
                              <input id="id_password" name="password" type="password" />
                            </p>
                            
                            <a style="text-decoration:underline;color:blue;" href="{% url 'reset_password' %}"> Forgot Password? </a>
                            
                   
                    </div>
        
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      <input type="submit" value="Login" class="btn btn-info"> 
                      
                    </div>
                    </form>
    </div>
  </div>
</div>

templates/elements/messages.html
{% load global_tags %}
{% if messages %}
<ul>
    {% for message in messages %}
        {% if message.tags %}
            <li  class="{{ message.tags }} {{ message.level|django_to_bootstrap_message_class }}" style="color:black;">
                {{ message }}
            </li>
        {% endif %}
    
    {% endfor %}
</ul>
{% endif %}

templates/elements/navbar_public.html
<div class="container">
        <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home_page' %}">Divorce Calcs</a>
        </div>

        <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                        
                         {% if request.path != '/sign-up/' %}
                        <li class="menuItem">
                        <a href="{% url 'sign_up_simple' %}" class="btn navbar-btn btn-danger" style="color:white;" role="button">Sign-Up</a>
                        </li>
                        {% endif  %}
                        <li class="menuItem"><a href="{% url 'about_public' %}">About</a></li>
                        <li class="menuItem"><a href="{% url 'home_page' %}#whatis">Benefits</a></li>
                        <li class="menuItem"><a href="{% url 'home_page' %}#screen">Screenshot</a></li>
                        <li class="menuItem"><a href="{% url 'login_simple' %}">Sign-In</a></li>
                       
                </ul>
        </div>
                   
</div>

templates/elements/page_id.html
$('body').append('<span id="page_id" page_id="{% block page_id %}base{% endblock page_id %}" style="display:none;"></span>');

templates/elements/pagination.html
{% load global_tags %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
      <li>
          <a href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
      </li>
    {% endif %}
        
    {% for p in pages %}
        <li><a href="{{ request.get_full_path|add_page_arg:p }}"> {{p}} </a></li>
      {% endfor %}
    
    {% if page.has_next %}
      <li>
        <a href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    {% endif %}
    
  </ul>
</nav>

templates/elements/refs_base.html
{% load static from staticfiles %}
<link href="{% static 'favicon.ico' %}" type="image/png" rel="icon"  />
<script src="{% static 'main.js' %}" type="text/javascript"  ></script>
<link href="{% static 'main.css' %}" type="text/css" rel="stylesheet" >

<script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"  crossorigin="anonymous">

        

templates/elements/refs_home_page.html
{% load static from staticfiles %} 

<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="Flatfy Free Flat and Responsive HTML5 Template ">
    <meta name="author" content="">

    

    <!-- Bootstrap core CSS -->
    
    <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
        <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"  crossorigin="anonymous">
        
 
    <!-- Custom Google Web Font -->
    <link href="{% static 'lib/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>
        
    <!-- Custom CSS-->
    <link href="{% static 'lib/css/general.css' %}" rel="stylesheet">
        
         <!-- Owl-Carousel -->
    <link href="{% static 'lib/css/custom.css' %}" rel="stylesheet">
        <link href="{% static 'lib/css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'lib/css/owl.theme.css' %}" rel="stylesheet">
        <link href="{% static 'lib/css/style.css' %}" rel="stylesheet">
        <link href="{% static 'lib/css/animate.css' %}" rel="stylesheet">
        
        <!-- Magnific Popup core CSS file -->
        <link rel="stylesheet" href="{% static 'lib/css/magnific-popup.css' %}"> 
        
        <script src="{% static 'lib/js/modernizr-2.6.2.min.js' %}"></script>  <!-- Modernizr /-->
        
        
        <!--[if lt IE 9]>
                <script src="{% static 'lib/js/html5shiv.js' %}"></script>
        <![endif]-->