apps/balance/urls.py
from django.conf.urls import url

from . import views

#/balance/
urlpatterns = [   
    url(r'^$',views.MainBalanceRedirectView.as_view(),name="main_redirect"),
    url(r'^(?P<year>[0-9]{4})/$',views.YearlyMonthBalanceView.as_view(),name="year"),    
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.MonthBalanceView.as_view(),name="details"),
     url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/clear/$',views.ClearMonthBalanceView.as_view(),name="clear"),
     url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/clear/changed/$',views.ClearMonthBalanceChangedView.as_view(),name="clear_changed"),
    
    ]

apps/expenses/urls.py
from django.conf.urls import include, url

from . import views

#/expenses/
urlpatterns = [
    
    url(r'^$', views.MainExpensesRedirectView.as_view(),name='main_redirect'),
    
    # expense
    url(r'^(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', views.ExpenseView.as_view(),name='details'),
    url(r'^add/$', views.AddExpenseView.as_view(),name='add'),
    url(r'^edit/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', views.EditExpenseView.as_view(),name='edit'),
    url(r'^delete/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', views.DeleteExpenseView.as_view(),name='delete'),
    url(r'^approve/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', views.ApproveExpenseView.as_view(),name='approve'),
    url(r'^change-balanced-month/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$',views.ChangeExpenceBalanceMonthView.as_view(),name='change_month_balance'),
    
    # ajax
    url(r'^ajax/multi-approve/$', views.expenses_multiple_approve,name='expenses_multi_approve'),
    
    # list views
    # GET arg ?approve=yes/no/all by=all/my/divorcee
    url(r'^monthly/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.MonthlyExpensesAllView.as_view(),name='monthly_all'),
    url(r'^monthly/my/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.MonthlyExpensesMyView.as_view(),name='monthly_my'),
    url(r'^monthly/divorcee/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.MonthlyExpensesDivorceeView.as_view(),name='monthly_divorcee'),
    
    
]

apps/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    
    url(r'^$',views.settings_redirect,name="main_settings_redirect"),
    url(r'^my/$',views.UserSettingsView.as_view(),name="user_settings"),
    url(r'^verify-password/$',views.auth_view,name="auth_user"),
    url(r'^verify-password/ajax$',views.auth_ajax,name="auth_user_ajax"),
    
    ]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles import views
from django.conf.urls.static import static

from django.contrib.auth import views as django_auth_views

from home.views import HomePageView
from apps.help import views as help_views
from apps.public.auth import views as auth_views
from apps.public.info import views as public_info_views
from apps.search.views import SearchView

urlpatterns = [
    # admin
    url(r'^%s/'%settings.ADMIN_URL, include(admin.site.urls)),
    
    # home
    url(r'^$', HomePageView.as_view(), name='home_page'),
    
    # auth
    url(r'^demo/$', auth_views.demo_account, name='demo_account'),
    url(r'^sign-up/$', auth_views.SignUpView.as_view(), name='sign_up_simple'),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login_simple'),
    url(r'^logout/$', auth_views.logout_user, name='logout_simple'),
    url(r'^reset-password/$',auth_views.password_reset_view,name="reset_password"),    
    
    # django auth
    url(r'^reset-password/done/$', django_auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        django_auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', django_auth_views.password_reset_complete, name='password_reset_complete'),
    
    # app modules
    url(r'^settings/', include('site_repo.apps.users.urls',namespace='users')),
    url(r'^expenses/', include('site_repo.apps.expenses.urls',namespace='expenses')),
    url(r'^balance/', include('site_repo.apps.balance.urls',namespace='balance')),   
    url(r'^search/$',SearchView.as_view(),name='search_view'),
    
    url(r'^how-to/$',help_views.IntroView.as_view(),name='intro'),
    
    # public info
    url(r'^about/$',public_info_views.AboutPublicView.as_view(),name="about_public"),
    url(r'^terms-of-service/$',public_info_views.TOSPublicView.as_view(),name="tos_public"),
    url(r'^privacy/$',public_info_views.PrivacyPolicyView.as_view(),name="privacy_policy_public")
]

if settings.DEBUG:
    urlpatterns += [url(r'^static/(?P<path>.*)$', views.serve),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
    
    

templates/base.html
{% load static from staticfiles %}


<!DOCTYPE html>

<html>

    <head>

        <title> {% block title %} {{ page_title }} {% endblock title %}</title>
        {% include "elements/refs_base.html" %}
        {% block additional_refs %} {% endblock additional_refs %}
        <script> 
                $(function() {
                        $('body').append('<span id="page_id" page_id="{% block page_id %}base{% endblock page_id %}" style="display:none;"></span>');
                        {% block ready_script %} {% endblock ready_script %}
                });                
        </script>
        <style type="text/css"> {% block embeded_style %} {% endblock embeded_style %} </style>

    </head>



    <body>
    
        <nav class="navbar navbar-default bavbar-fixed-top">
            <div class="container-fluid">
                {% block top_nav %} {% endblock top_nav %}
            </div>
        </nav>
    
        {% block body %} {% endblock body %}
            
    </body>


</html>

templates/base_login.html
{% extends "base.html" %}

{% block ready_script %}
    {{ block.super }}
    
    {% if DEMO %}    
        $('.save').on('click',function(event){
        event.preventDefault();
        alert("Demo account can only view data. Sign-up for free to get your own account");
            });    
    {% endif %}
    
                    var csrftoken = getCookie('csrftoken');
                    $.ajaxSetup({
                    beforeSend: function(xhr, settings) {
                       
                            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                        
                    }
                });
    set_sidebar({% block sidebar_item %} "expenses" {% endblock sidebar_item %});
    $(".dropdown-menu > li ").on("click",update_bootstrap_dropdown_button_by_selection);
    $("#searchGo").on("submit",function(){
            q=$('#search_query')[0].value;
            url = {% url 'search_view' %}+"?q=" + q;
            if (q.length>0){document.location=url;}
            return false;
            });
            style_elements();
{% endblock ready_script %}


{% block top_nav %}

        {% if DEMO %}
        <a href="{% url 'sign_up_simple' %}" class="btn navbar-btn btn-danger navbar-left" style="color:white;font-weight:bold;" role="button">
            Sign-Up for Free!
        </a>
        
        {% endif %}

       <p class="navbar-text navbar-right" style="padding-right:10px;"> 
       {% if DEMO %}
             Demo Account: John (divorcee Ashley)
        {% else  %}
            Signed in: {{ request.user.username }} 
        {% endif %}
       </p>
        <a href="{% url 'logout_simple' %}" class="btn navbar-btn btn-default navbar-right" id="logout"> Logout </a> 
        <a href="{% url 'expenses:add' %}" class="btn navbar-btn btn-default navbar-right" id="add_expense">
            <span  class="glyphicon glyphicon-plus" style="padding-right:5px;" aria-hidden="true"></span>
            Add Expense...
        </a>  
        <form class="navbar-form navbar-right" role="search" id="searchGo" >
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search..." id="search_query">
            </div>
            <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>  Go!      
            </button>
        </form>
                
        </div>
        </div>
{% endblock top_nav %}


{% block body %}

    <div class="page-header">
        <h1>
           <span>{% block page_title %} {% endblock page_title %}   </span>
           <span style="margin-left:50px;">{% block page_nav %} {% endblock page_nav %}   </span>
           
        </h1>        
    </div>
    
    <div class="col-xs-10">
        {% block main_content %} {% endblock main_content %}
    </div>
    
    <div class="col-xs-2">    
        <ul class="nav nav-pills nav-stacked">
            <li role="presentation" id="sidebar-expenses">
                <a href="{% url 'expenses:main_redirect' %}">
                    <span class="glyphicon glyphicon-usd" style="padding-right:15px;" aria-hidden="true" id="side_bar_expenses"></span> Expenses
                </a>
            </li>
            <li role="presentation" id="sidebar-balance"> 
                <a href="{% url 'balance:main_redirect' %}"> 
                    <span  class="glyphicon glyphicon-calendar" style="padding-right:15px;" aria-hidden="true"></span>Monthly Balance 
                </a>
            </li>
            <li role="presentation" id="sidebar-settings">
                <a href="{% url 'users:main_settings_redirect' %}">
                   <span class="glyphicon glyphicon-user" style="padding-right:15px;" aria-hidden="true"></span>  Settings 
                </a>
            </li>
            <li role="presentation" id="sidebar-how-to">
                <a href="{% url 'intro' %}">
                   <span class="glyphicon glyphicon-ok" style="padding-right:15px;" aria-hidden="true"></span>  How-To 
                </a>
            </li>
        </ul>
    </div>
    
<div class="col-xs-10">
    {% if paginate %}   
        {% include "elements/pagination.html" %}        
    {% endif %}           
</div>

{% endblock body %}

templates/base_public.html
{% extends "base.html" %}
{% load static from staticfiles %}


{% block additional_refs %}
<link href="{% static 'lib/css/style.css' %}" rel="stylesheet">
{% endblock additional_refs %}

{% block ready_script %}

style_elements()
{% endblock ready_script %} 


        {% block top_nav %}
                {% include "elements/navbar_public.html" %}
        {% endblock top_nav %}
        

{% block body %}




    {% block main_content %}{% endblock main_content %}
    
{% endblock body %}

templates/it_works.html
{% extends "base_public.html" %}
{% load static from staticfiles %}


{% block main_content %}

    <div class="content">
        <h1> {{ intro }} </h1>
        <p> Your IP is {{ ip }} </p>
        <p> DEBUG is {{ is_debug }} </p>
    </div>
            
    
    <div class="content">    
        <h3> Static files: </h3>
        <p> Click the button, if static files work, an alert should appear </p>
        <button type="button" onClick="show_static_info();" class="info"> Static Files Info </button>    
    </div>
    
    <div class="content">
        <h3> Image from static files: </h3>
        <p> Directory for the site pre-prepared, optimized media (e.g. logo, favicon, icons)</p>
        <img src="{% static 'powered-by-django.gif' %}">
    </div>
    
    <div class="content">
        <h3> Image from media uploads: </h3>
        <p> Directory for the users' uploaded media (e.g. avatars)</p>
        <img src="{{ MEDIA_URL }}avatar.png"  class="avatar"/>
    </div>
    
    
<p> The site is powered by {{ DJANGO_VER }}  </p>    


{% endblock main_content %}