apps/balance/urls.py
from django.conf.urls import url

from . import views

#/balance/
urlpatterns = [   
    url(r'^$',views.MainBalanceRedirectView.as_view(),name="main_redirect"),
    url(r'^(?P<year>[0-9]{4})/$',views.YearlyMonthBalanceView.as_view(),name="year"),    
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.MonthBalanceView.as_view(),name="details"),
     url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/clear/$',views.ClearMonthBalanceView.as_view(),name="clear"),
     url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/clear/changed/$',views.ClearMonthBalanceChangedView.as_view(),name="clear_changed"),
    
    ]

apps/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    
    url(r'^$',views.settings_redirect,name="main_settings_redirect"),
    url(r'^my/$',views.UserSettingsView.as_view(),name="user_settings"),
    url(r'^verify-password/$',views.auth_view,name="auth_user"),
    url(r'^verify-password/ajax$',views.auth_ajax,name="auth_user_ajax"),
    
    ]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles import views
from django.conf.urls.static import static

from django.contrib.auth import views as django_auth_views

from home.views import HomePageView
from apps.help import views as help_views
from apps.public.auth import views as auth_views
from apps.public.info import views as public_info_views
from apps.search.views import SearchView

urlpatterns = [
    # admin
    url(r'^%s/'%settings.ADMIN_URL, include(admin.site.urls)),
    
    # home
    url(r'^$', HomePageView.as_view(), name='home_page'),
    
    # auth
    url(r'^demo/$', auth_views.demo_account, name='demo_account'),
    url(r'^sign-up/$', auth_views.SignUpView.as_view(), name='sign_up_simple'),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login_simple'),
    url(r'^logout/$', auth_views.logout_user, name='logout_simple'),
    url(r'^reset-password/$',auth_views.password_reset_view,name="reset_password"),    
    
    # django auth
    url(r'^reset-password/done/$', django_auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        django_auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', django_auth_views.password_reset_complete, name='password_reset_complete'),
    
    # app modules
    url(r'^settings/', include('site_repo.apps.users.urls',namespace='users')),
    url(r'^expenses/', include('site_repo.apps.expenses.urls',namespace='expenses')),
    url(r'^balance/', include('site_repo.apps.balance.urls',namespace='balance')),   
    url(r'^search/$',SearchView.as_view(),name='search_view'),
    
    url(r'^how-to/$',help_views.IntroView.as_view(),name='intro'),
    
    # public info
    url(r'^about/$',public_info_views.AboutPublicView.as_view(),name="about_public"),
    url(r'^terms-of-service/$',public_info_views.TOSPublicView.as_view(),name="tos_public"),
    url(r'^privacy/$',public_info_views.PrivacyPolicyView.as_view(),name="privacy_policy_public")
]

if settings.DEBUG:
    urlpatterns += [url(r'^static/(?P<path>.*)$', views.serve),]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
    
    

apps/users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

class UserSettings(models.Model):
    
    user = models.OneToOneField(User,related_name="settings")
    send_mail_when_divorcee_approve = models.BooleanField(default=False)
    send_mail_when_divorcee_balance = models.BooleanField(default=False)
    base_divorcee_participate = models.IntegerField(default=50)

@receiver(post_save,sender=User)
def new_user_settings(*args,**kwargs):
    
    if not kwargs['created']:
        return
    
    settings = UserSettings(user=kwargs['instance'])
    settings.save()

apps/users/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.views import password_change
from ...lang import forms_login as lang_forms_login

class UserSettingsForm(forms.Form):
    
    send_mail_when_divorcee_approve = forms.BooleanField(label=lang_forms_login.mail_approve,required=False)
    send_mail_when_divorcee_balance = forms.BooleanField(label=lang_forms_login.mail_balance,required=False)
    user_email = forms.EmailField(required=False,label="Email")
    base_divorcee_participate = forms.IntegerField(label=lang_forms_login.base_participate)
    password1 = forms.CharField(required=False,widget=forms.PasswordInput(),label="New Password")                                                                     
    password2 = forms.CharField(required=False,widget=forms.PasswordInput(),label="New Password Again")
    
    def clean(self):
        
        cleaned_data = super(UserSettingsForm,self).clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        
        if (password1 != "" or password2 != "") and (password1 != password2):
                raise forms.ValidationError(message="password_not_match")
        
        return
            
    
    def save(self,user):
        
        password_changed = False
        if self.cleaned_data['password1'] != "" and self.cleaned_data['password1'] != None:
            user.set_password(self.cleaned_data['password1'])
            password_changed = True
                    
        if self.cleaned_data['user_email'] != "" and self.cleaned_data['user_email'] != None:
            user.email = self.cleaned_data['user_email']
            
        user.settings.send_mail_when_divorcee_approve = self.cleaned_data['send_mail_when_divorcee_approve']
        user.settings.send_mail_when_divorcee_balance = self.cleaned_data['send_mail_when_divorcee_balance']
        user.settings.base_divorcee_participate = self.cleaned_data['base_divorcee_participate']
        
        user.save()
        user.settings.save()
        
        return password_change
            
            
class PasswordForm(forms.Form):
    
    password = forms.CharField(max_length=36)
        
        
        
        
        
        
    
    
    
    

apps/users/views.py
import datetime
import pickle
import json
from django.conf import settings
from django.contrib.auth import update_session_auth_hash,authenticate
from django.core.urlresolvers import reverse,reverse_lazy
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.views import generic

from . import API
from . import forms


def settings_redirect(request):
    
    if API.require_auth_to_user_settings(request):
        url = reverse("users:auth_user")
    else:
        url = reverse("users:user_settings")
        
    return redirect(url)

def auth_view(request):
    
    return render(request,"users/auth_user.html")
    
def auth_ajax(request):
    
    form = forms.PasswordForm(request.POST)
    if form.is_valid():
        u = authenticate(username=request.user.username,
                         password=form.cleaned_data['password'])
        if u != None:
            request.session['last_authenticated'] = pickle.dumps(datetime.datetime.now())
        response = {'password':'success'} if u != None else {'password':'fail'}
    else:
        response = {'password':'fail'}
        
    return HttpResponse(json.dumps(response), content_type="application/json")
        

class UserSettingsView(generic.FormView):
    
    template_name = "users/user_settings.html"
    form_class = forms.UserSettingsForm
    success_url = reverse_lazy("expenses:main_redirect")
    
    def get(self,request,*args,**kwargs):
        
        if API.require_auth_to_user_settings(self.request):
            return redirect((reverse("users:auth_user")))
        return super(UserSettingsView,self).get(request,*args,**kwargs)
    
    def get_form_kwargs(self,*args,**kwargs):
        
        kwargs = super(UserSettingsView,self).get_form_kwargs(*args,**kwargs)
        kwargs['label_suffix'] = ""
        return kwargs
        
    def get_initial(self,*args,**kwargs):
        
        user = self.request.user
        self.initial = {'send_mail_when_divorcee_approve':user.settings.send_mail_when_divorcee_approve,
                        'send_mail_when_divorcee_balance':user.settings.send_mail_when_divorcee_balance,
                        'base_divorcee_participate':user.settings.base_divorcee_participate,
                        'user_email':self.request.user.email}
    
        return super(UserSettingsView,self).get_initial() 
    
    
    def form_valid(self, form):
        
        password_changed = form.save(self.request.user)
        if password_changed:
            update_session_auth_hash(self.request,self.request.user)
        
        return super(UserSettingsView,self).form_valid(form)
    
    
               
               
    

templates/users/auth_user.html
{% extends "base_login.html" %}
{% load static from staticfiles %}

{% block sidebar_item %} "settings" {% endblock sidebar_item %}
{% block page_title %} Enter password to change settings{% endblock page_title %} 

{% block ready_script %} 
    {{ block.super }}

$("#send").on("click",function(){
                                $.ajax(
                                        {type:"POST",
                                        url: "{% url 'users:auth_user_ajax' %}",
                                        data: {"password":$("#password").val()},
                                        global: false,
                                        success: function(data){
                                                        if (data['password']=='success'){ 
                                                                                                    $("#password_success").show();
                                                                                                    $("#password_fail").hide();}
                                                                                                    else {
                                                                                                    $("#password_success").hide();
                                                                                                    $("#password_fail").show();}
                                                                },
                                     error: function (){}
                                   });
                });
    
    
{% endblock %}

{% block main_content %}

<div class="col-xs-6">
<div style="margin-bottom:20px;">
<h4> Enter Password: </h4>
<input id="password" name="password" type="password" class="form-control">

<br>
<button id="send" class="btn btn-primary"> Send </button>
</div>

<div id="password_success" style="display:none;">
<div class="alert alert-info" role="alert">Password Verified!</div>
<a href="{% url 'users:user_settings'%}" class="btn btn-success" role="btn"> Go to settings page </a>
</div>

<div id="password_fail" style="display:none;">
<div class="alert alert-danger" role="alert">Password failed, try again</div>
</div>


</div>
{% endblock main_content %}

templates/users/user_settings.html
{% extends "base_login.html" %}
{% load static from staticfiles %}

{% block sidebar_item %} "settings" {% endblock sidebar_item %}
{% block page_title %} User Settings{% endblock page_title %} 
    
{% block main_content %}



<form action="" method="POST" class="col-xs-6">
<h4 > <span class="label label-info"> Details </span> </h4>
    <p>
    {{ form.send_mail_when_divorcee_approve }}
    {{ form.send_mail_when_divorcee_approve.label_tag }}
    {{ form.send_mail_when_divorcee_approve.errors }}
    </p>
    
    <p>
    {{ form.send_mail_when_divorcee_balance }}
    {{ form.send_mail_when_divorcee_balance.label_tag }}
    {{ form.send_mail_when_divorcee_balance.errors }}
    </p>
    
    <p>
    {{ form.user_email.label_tag }}
    {{ form.user_email }}
    {{ form.user_email.errors }}
    
    </p>
    
    <p>
    {{ form.base_divorcee_participate.label_tag }}
    {{ form.base_divorcee_participate }} 
    {{ form.base_divorcee_participate.errors }}
    You can change this value when actually entering the expense
    </p>
    

   
   
   <h4 > <span class="label label-info"> Change password </span> </h4>
   <p>
    {{ form.password1.label_tag }}
    {{ form.password1 }}
    {{ form.password1.errors }}
    leave blank if you don't want to change password
    </p>
    
    <p>
    {{ form.password2.label_tag }}
    {{ form.password2 }}
    {{ form.password2.errors }}
     leave blank if you don't want to change password
    </p>

    {% csrf_token %}
    
    <a href="{% url "expenses:main_redirect" %}" class="btn btn-danger" role="button"> Cancel </a>
    <input type="submit" value="Save" class="btn btn-success save"> 
        
</form>

<div class="col-xs-6">
<div class="panel panel-info">
  <div class="panel-body panel-heading">
    <h3 class="panel-title">
    {% if request.user.divorcee %}    
        Account Code
    {% else %}
        Invite divorcee to sign up with the following code:
    {% endif %}
    
    
    </h3>
  </div>
  <div class="panel-footer">
    {{ request.user.account.account_code }}
  </div>
</div>
</div>
{% endblock main_content %}